### ISSUE TITLE
A remind feature

### ISSUE THREAD

**Issue by mp7786** [ClemsonCPSC-Discord/ClemBot#111]
Any ideas of what it should support.

**Comment by Jay-Madden** [comment]
so aside from the scheduling concerns we should def allow for being reminders AT a certain time as well as reminders X amount of time in the future

**Comment by Jay-Madden** [comment]
Each reminder will be wrapped in a seperate task and referenced by id

**Comment by Jay-Madden** [comment]
Scheduler for this cog wass added in #124

**Comment by mp7786** [comment]
Merged in #297
