### ISSUE TITLE
Revamp Help command

### ISSUE THREAD

**Issue by Jay-Madden** [ClemsonCPSC-Discord/ClemBot#127]
The default d.py help command is ugly and a way to make it pretty would be very nice

**Comment by Exper1mental** [comment]
Ideally the help command should also include command arguments e.g. `role add`.

Alternatively, command arguments could be provided on a separate list by implementing something like `$help role`, which returns what `role` does and what its arguments are.

Could also have individual help message for each argument. e.g. `$help role create` would tell the user what the `create` argument does (and what its alias, `add` is)

**Comment by Jay-Madden** [comment]
By Default the help command does. It reads the pydoc comments on the decorated command methods and prints those out. We need to override this behavior to change its visuals. But the concept will be the same

**Comment by Exper1mental** [comment]
Ok. Going to look into implementing this one...

**Comment by Jay-Madden** [comment]
This is a much higher priority now that #210 is merged

**Comment by Exper1mental** [comment]
I got stuck trying to resolve an issue where the revamped help command didn't work as intended (I think it was for sub-commands that it had issues?). Probably won't be able to look at it until after finals. Could share what I had if desired

**Comment by Jay-Madden** [comment]
Feel free to pr what you have and we can take a look, or ping me in the test servee
