### ISSUE TITLE
Make Role Assignment Non-Case Sensitive

### ISSUE THREAD

**Issue by Exper1mental** [ClemsonCPSC-Discord/ClemBot#129]
Should be pretty self explanitory.

**_Normal Example_**
Roles:
1. Freshman
2. Sophomore
...

User: `!role sophomore`

Bot: `Role assigned: Sophomore`

 
 
**_Special Case Example_**
Roles:
1. JUNIOR
2. junior

Ignoring case, there are two possible roles the user is requesting. In this situation, my thought is to perform a case-sentitive evaluation of the user input corresponding to the roles. If not role exists, return an error listing the possible roles the users might've been requesting. Since there are two possible roles the user is requesting, the bot will need to 

_Special case example 1:_
User: `!role Junior`
Bot: `Error, role not found. Two possible roles: 1. JUNIOR or 2. junior`

Emojis could be used to have the user select which role they wanted.

_Special case example 2:_
User: `!role junior`
Bot: `Role assigned: junior`

For this special case, I'm wondering if there should be a warning even if the user types in the case-senseitive role to inform them of another possible role they might otherwise be unaware of.

**Comment by Jay-Madden** [comment]
Excellent write up, implementing should not be too involved

**Comment by Jay-Madden** [comment]
And if there is a conflict then we should probably tell them what their options are

**Comment by Exper1mental** [comment]
**Draft pull request created**:
https://github.com/ClemsonCPSC-Discord/ClemBot/pull/130
