### ISSUE TITLE
Source Command Drops Last Line of Code

### ISSUE THREAD

**Issue by Exper1mental** [ClemsonCPSC-Discord/ClemBot#142]
Small bug I noticed when asking the source command to print specific lines of code. The last line seems to get dropped.

Example `<bot_prefix>source example_cog.py 1 3` would only print lines 1 and 2:
```python
1:    #what the bot does 
2:    import logging
```

**Comment by Jay-Madden** [comment]
when i originally wrote it it, i wrote it to be range inclusive exclusive but that really doesnt make a ton sense and should probably be changed

**Comment by Exper1mental** [comment]
Should this be closed since the source command no longer outputs the source in Discord?
