### ISSUE TITLE
Add alias to the designated channels cog

### ISSUE THREAD

**Issue by Jay-Madden** [ClemsonCPSC-Discord/ClemBot#144]
The alias "set" would work work really well on the !channels add command

**Comment by tyler-macinnis** [comment]
Just curious, are there any other commands that should potentially have aliases? Or is this basically resolved?

**Comment by Jay-Madden** [comment]
i cant think of any off the top of my head but im sure there are some, im of the opinion that aliases should be used very liberally to allow for the widest range of use. So if you see any that you think should be added feel free to ping me in the server or just pr it

**Comment by Jay-Madden** [comment]
ive kinda left them off of my priorities on purpose as they are a great thing people can add to get comfortable with the pr workflow and see actual results in the server

**Comment by tyler-macinnis** [comment]
Yeah, it's a very good first issue for people to do. I don't know of any at the moment but I bet there's some out there.

**Comment by smathep** [comment]
@Jay-Madden This was implemented in #180 and this should be marked closed

**Comment by Jay-Madden** [comment]
ope ty
