### ISSUE TITLE
Add a teacher feature to the !grades command

### ISSUE THREAD

**Issue by Jay-Madden** [ClemsonCPSC-Discord/ClemBot#156]
the grades command has been very popular and helpful. However, it is often wanted to compare individual teachers to make an informed decision on who to take. I propose if possible we add a way to get professor specific info

**Comment by Jay-Madden** [comment]
cc @Nathan-Binkley

**Comment by Nathan-Binkley** [comment]
I can add a "prof" command to just do professor stuff.

Just let me know what other kinds of data you'd like presented.

**Comment by Jay-Madden** [comment]
Closed in #218
