### ISSUE TITLE
Invalid filenames using datetime.datetime.utcnow() on Windows

### ISSUE THREAD

**Issue by kspalm** [ClemsonCPSC-Discord/ClemBot#182]
The !crab command saves the .gif file with a filename that contains invalid characters when the bot is running on Windows.
The `datetime.datetime.utcnow()` needs to be formatted with `strftime()`to remove colons (and maybe spaces?) instead of being used directly in a format string.

**Comment by Jay-Madden** [comment]
cc @paynejordand

**Comment by paynejordand** [comment]
Rather than format using strftime() I just grabbed the microseconds from it, because that's really all that matters.
`datetime.datetime.utcnow().microseconds`
It ends up having the same effect as formatting with the %f format modifier.

**Comment by Jay-Madden** [comment]
if you want to see an example of this fix i had this same problem in `__main__.py` you can look there for an example if youd like

**Comment by paynejordand** [comment]
I felt it wasn't worth the effort tbh since it's deleted within a couple seconds typically

**Comment by Jay-Madden** [comment]
as long as it will run on windows. the : in the name meant it crashed on windows

**Comment by Jay-Madden** [comment]
fixed in #215
