### ISSUE TITLE
When trash_bin reaction is removed, all reactions are removed

### ISSUE THREAD

**Issue by Nathan-Binkley** [ClemsonCPSC-Discord/ClemBot#199]
Not sure if this is intentional.

**Comment by Nathan-Binkley** [comment]
Replication steps: Bot posts response with trash bin in reactions (Standard for removal). Have people respond randomly with different reactions. Upon the automatic removal of the trash bin reaction, all reactions disappear.

**Comment by Jay-Madden** [comment]
Ha this is known, it's being tracked in #194
