### ISSUE TITLE
Trashcan doesn't work for tag lists

### ISSUE THREAD

**Issue by Exper1mental** [ClemsonCPSC-Discord/ClemBot#230]
The trashcan doesn't delete tag list messages
![image](https://user-images.githubusercontent.com/14143235/101729358-06db5c00-3a86-11eb-9f10-bf4873e095cc.png)

Side comment: Not sure if this is intended or not but most !role, !roles, and !help messages don't have a delete trashcan.

**Comment by mp7786** [comment]
Could this be related to how the paginate and the delete service interact?

**Comment by Jay-Madden** [comment]
fixed in 8af21f4cc8bcc7087f1c55623cb6c21a339c900c
