### ISSUE TITLE
Define cog errors out bot initialization if merriam key not present

### ISSUE THREAD

**Issue by Exper1mental** [ClemsonCPSC-Discord/ClemBot#233]
The Define Cog prevents the initialization of the bot if the Merriam key is not present in BotSecrets.json.

This is a _very_ easy fix. Instead of retrieving the API key at initialization of the bot, it should be retrieved when the command is called, like the GIPHY cog.

~I can submit a small commit with a fix if desired.~
Pull request #236 addressing this has been submitted.

**Comment by Jay-Madden** [comment]
closed in #236
