### ISSUE TITLE
Add a Translator Cog

### ISSUE THREAD

**Issue by Exper1mental** [ClemsonCPSC-Discord/ClemBot#243]
Title says it all. The idea is a translator cog for converting text in one language to another. Shouldn't be too hard to implement.

Calling it could look like something along the lines of:
```
!translate <input language> <output language> <input text>
```

Example:
```
!translate french english "Vive La France"
```
Would yield:
```
Long live France
```

**Comment by Jay-Madden** [comment]
I'm open to the idea, do you have a specific api in mind?

**Comment by Exper1mental** [comment]
Not in particular, but it looks like there is a decent selection to choose from that are free to use, including with language autodetection abilities.

**Comment by Jay-Madden** [comment]
Well lets def start perusing different apis

**Comment by smathep** [comment]
What about Azure? We can get it free for now as students and they have a free tier for up to 2 million characters translated per month

**Comment by Exper1mental** [comment]
Closing. Added per #250.
