### ISSUE TITLE
Paginate For Field Titles

### ISSUE THREAD

**Issue by Exper1mental** [ClemsonCPSC-Discord/ClemBot#246]
For the weather cog, I'm making, I ideally need to be able to change the field title corresponding to each page. The first page is the current conditions, the second is the first part of the 7-day forecast, the third is the second part of the forecast.

A potential challenge is that this should ideally be implemented such that changing field titles are supported without requiring them (meaning, if a string is provided for the field title, all pages will use that instead)

**Comment by Jay-Madden** [comment]
This was actually already implemented in #249 the paginate server can now take an arbitrary list of embeds and display them in order. the embeds themselves can be completely different its up to the caller
