### ISSUE TITLE
Command to have clembot return join date

### ISSUE THREAD

**Issue by smathep** [ClemsonCPSC-Discord/ClemBot#280]
As a mod on a server, it can be annoying when trying to tell if an account is trolling, and something very helpful would be easy access to when a user joins a server.

I propose a command that you can supply a user's @ or simply their id and ClemBot can return when they joined the server.

So far the other option is using ClemBot's user join log and searching for when that user joined but can be time consuming or troublesome if the user has changed nicknames or usernames.

**Comment by Jay-Madden** [comment]
yes, this is part of a larger !info command that ive been wanting

**Comment by smathep** [comment]
What would you like the info command to show?

**Comment by Jay-Madden** [comment]
![image](https://user-images.githubusercontent.com/25359755/115942047-2c399700-a476-11eb-8fde-0cc0c7884612.png)
stuff like this

**Comment by smathep** [comment]
Are you looking for all of that information, including guild stats like rank?

**Comment by smathep** [comment]
and do we want to have some information locked to designated groups with claims, or the entire command locked to specific claims permissions?

**Comment by Jay-Madden** [comment]
i dont think we want rank at this moment tbh, some other more general info could be cool, something like total messages
