### ISSUE TITLE
Calculator Command Can't Handle Commas?

### ISSUE THREAD

**Issue by Exper1mental** [ClemsonCPSC-Discord/ClemBot#281]
When using the calculator, it appears it doesn't handle commas; or rather, it _ignores_ numbers included before commas. 

e.g. `!calc 1,100 * 2` outputs `200.0`

**Comment by Jay-Madden** [comment]
cc @mp7786

**Comment by zepthro** [comment]
Can we close this issue. Issue seems resolved since #282.

**Comment by Jay-Madden** [comment]
Closed in #282
