### ISSUE TITLE
Weather cog returns input for cords (0,0) when given an invalid input

### ISSUE THREAD

**Issue by Emimendoza** [ClemsonCPSC-Discord/ClemBot#288]
![image](https://user-images.githubusercontent.com/24688719/108946364-e3a36000-7623-11eb-91b5-331b1c949617.png)

**Comment by Exper1mental** [comment]
Yeah I probably should just have it return a message saying "Error: invalid location" instead of returning that, which is literally the weather at longitude 0, latitude 0:
![image](https://user-images.githubusercontent.com/14143235/113159871-f1dc3180-920a-11eb-9b6d-4f4a2e7cbe0b.png)
