### ISSUE TITLE
Tag Cog: Add ability to claim unowned tags

### ISSUE THREAD

**Issue by Exper1mental** [ClemsonCPSC-Discord/ClemBot#349]
The title says it all. Tags that are no longer "owned" for whatever reason (owner left server, banned, system error, etc.) should be "claimable" by other users.

This would tie in well with #348 if the ability to see a list of unowned tags was added. There could be a checkbox reaction for claiming tags quickly and easily in addition to deleting them.

It would also be good to fix the existing error that occurs when running `!tag info` on a tag that is not owned so that it says "Tag unowned, would you like to claim it?" while displaying tag info as well.

**Comment by Jay-Madden** [comment]
yes this is the number one tag related thing that needs to be added
