### ISSUE TITLE
A calculator feature

### ISSUE THREAD

**Issue by mp7786** [ClemsonCPSC-Discord/ClemBot#65]
I noticed that several channels on the Discord could use a simple calculator as those classes are heavier in math. What specific features and functionality would you like to see?

**Comment by Jay-Madden** [comment]
A simple expression evaluator is a good place to start, something that can do things like 
`1 + 4(3/2)`
we can start thinking about other things after that

**Comment by Jay-Madden** [comment]
Closed in #96
