### ISSUE TITLE
Currently there is no way to tell the bot to delete its own embed

### ISSUE THREAD

**Issue by Jay-Madden** [ClemsonCPSC-Discord/ClemBot#88]
We should have a utility that allows for a user to react with an emote that tells ClemBot to delete its message. To avoid cluttering up the channels

**Comment by Exper1mental** [comment]
Not sure how far along this is.

My though is you could add a reaction (e.g. 🗑️ `:wastebasket:`) to deletable message (similar to what I've done for using emoji reactions to select roles of different case with the same letters).

If a user, admin/moderator, or the owner of the message calling the bot selects the reaction, the message is deleted. Makes it super easy to use. Limiting who can delete the message could be handy on more active servers to prevent other users deleting the message before you have time to respond to the bot.

**Comment by mp7786** [comment]
Currently that is the state of this service. This service will by default allow for the owner of the message and any admins to delete the message. It will also support specifying custom roles that are allowed to delete. It will also support multiple message deletions from one message. For example the source code cog can fill the screen by sending separate very large messages. This service will allow deletion of all the messages from one reaction.

**Comment by Jay-Madden** [comment]
pr in #164
